import type { Workflow } from "@/lib/types/workflow";

const now = new Date().toISOString();

/**
 * End-to-end template listed in `spec.md` (Proposal-to-Delivery).
 * Positions are layout hints for the visual editor.
 */
export const fullProposalToDelivery: Workflow = {
  id: "wf_proposal_to_delivery",
  name: "Proposal to Delivery (full template)",
  version: "1.0.0",
  createdAt: now,
  updatedAt: now,
  description: "Signed proposal to delivery artifacts, scheduling, field updates, and weekly report.",
  metadata: { graphVersion: "1.0.0" },
  nodes: [
    {
      id: "artifact_proposal",
      type: "artifact",
      position: { x: 40, y: 80 },
      data: { name: "proposal.md", fileName: "proposal.md", artifactType: "md", status: "updated", notes: "external — signed proposal source" },
    },
    {
      id: "skill_create_task_list",
      type: "skill",
      position: { x: 280, y: 60 },
      data: {
        name: "create_task_list",
        fileName: "create_task_list.yaml",
        inputs: ["proposal.md"],
        outputs: ["tasks.md"],
        requires: ["proposal.exists"],
        produces: ["tasks.exists"],
        validations: ["tasks include scope and assumptions"],
        tags: ["planning"],
        enabled: true,
        version: 1,
        description: "Generate project tasks from the signed proposal",
      },
    },
    {
      id: "artifact_tasks",
      type: "artifact",
      position: { x: 520, y: 60 },
      data: { name: "tasks.md", fileName: "tasks.md", artifactType: "md", status: "missing" },
    },
    {
      id: "skill_assign_technician",
      type: "skill",
      position: { x: 520, y: 200 },
      data: {
        name: "assign_technician",
        fileName: "assign_technician.yaml",
        inputs: ["tasks.md"],
        outputs: ["technician_assignment.md"],
        requires: ["tasks.exists"],
        produces: ["technician_assignment.exists"],
        validations: ["technician and region recorded"],
        tags: ["assignment"],
        enabled: true,
        version: 1,
        description: "Record technician selection (human step represented as a reviewable skill)",
      },
    },
    {
      id: "artifact_tech",
      type: "artifact",
      position: { x: 760, y: 200 },
      data: { name: "technician_assignment.md", fileName: "technician_assignment.md", artifactType: "md", status: "missing" },
    },
    {
      id: "skill_gen_schedule",
      type: "skill",
      position: { x: 1000, y: 60 },
      data: {
        name: "generate_schedule",
        fileName: "generate_schedule.yaml",
        inputs: ["tasks.md", "technician_assignment.md"],
        outputs: ["schedule.md"],
        requires: ["tasks.exists", "technician_assignment.exists"],
        produces: ["schedule.exists", "schedule.valid"],
        validations: ["all tasks have dates", "no unassigned task remains"],
        tags: ["scheduling"],
        enabled: true,
        version: 1,
        description: "Build schedule from tasks and assignment",
      },
    },
    {
      id: "artifact_schedule",
      type: "artifact",
      position: { x: 1240, y: 60 },
      data: { name: "schedule.md", fileName: "schedule.md", artifactType: "md", status: "missing" },
    },
    {
      id: "skill_process_updates",
      type: "skill",
      position: { x: 1000, y: 280 },
      data: {
        name: "process_technician_update",
        fileName: "process_technician_update.yaml",
        inputs: ["schedule.md"],
        outputs: ["updates.md"],
        requires: ["schedule.exists"],
        produces: ["updates.current"],
        validations: ["updates reflect last known field work"],
        tags: ["field"],
        enabled: true,
        version: 1,
        description: "Ingest technician status into updates.md",
      },
    },
    {
      id: "artifact_updates",
      type: "artifact",
      position: { x: 1240, y: 280 },
      data: { name: "updates.md", fileName: "updates.md", artifactType: "md", status: "missing" },
    },
    {
      id: "skill_weekly",
      type: "skill",
      position: { x: 1480, y: 180 },
      data: {
        name: "generate_weekly_report",
        fileName: "generate_weekly_report.yaml",
        inputs: ["tasks.md", "schedule.md", "updates.md"],
        outputs: ["weekly_report.md"],
        requires: ["tasks.exists", "schedule.exists", "updates.exists"],
        produces: ["weekly_report.exists", "weekly_report.consistent"],
        validations: ["report covers active tasks and schedule dates"],
        tags: ["reporting"],
        enabled: true,
        version: 1,
        description: "Create weekly project report",
      },
    },
    {
      id: "artifact_report",
      type: "artifact",
      position: { x: 1720, y: 180 },
      data: { name: "weekly_report.md", fileName: "weekly_report.md", artifactType: "md", status: "missing" },
    },
  ],
  edges: [
    { id: "e_in_1", source: "artifact_proposal", target: "skill_create_task_list", edgeType: "input" },
    { id: "e_out_1", source: "skill_create_task_list", target: "artifact_tasks", edgeType: "output" },
    { id: "e_as_in", source: "artifact_tasks", target: "skill_assign_technician", edgeType: "input" },
    { id: "e_as_out", source: "skill_assign_technician", target: "artifact_tech", edgeType: "output" },
    { id: "e_sch_in1", source: "artifact_tasks", target: "skill_gen_schedule", edgeType: "input" },
    { id: "e_sch_in2", source: "artifact_tech", target: "skill_gen_schedule", edgeType: "input" },
    { id: "e_sch_out", source: "skill_gen_schedule", target: "artifact_schedule", edgeType: "output" },
    { id: "e_pu_in", source: "artifact_schedule", target: "skill_process_updates", edgeType: "input" },
    { id: "e_pu_out", source: "skill_process_updates", target: "artifact_updates", edgeType: "output" },
    { id: "e_w_in1", source: "artifact_tasks", target: "skill_weekly", edgeType: "input" },
    { id: "e_w_in2", source: "artifact_schedule", target: "skill_weekly", edgeType: "input" },
    { id: "e_w_in3", source: "artifact_updates", target: "skill_weekly", edgeType: "input" },
    { id: "e_w_out", source: "skill_weekly", target: "artifact_report", edgeType: "output" },
  ],
};
