import { buildEdgesFromContracts } from "@/lib/graph/wire-from-contracts";
import { syncSkillContractsFromGraph } from "@/lib/graph/edge-helpers";
import type { GenerationResponse } from "@/lib/ai/schema";
import type { ProposalNode, Workflow } from "@/lib/types/workflow";

const uid = () => crypto.randomUUID().slice(0, 8);

function proposalNodeBase(name: string, proposedDefinition: Record<string, unknown>, proposalType: ProposalNode["data"]["proposalType"]): ProposalNode {
  return {
    id: `proposal_${crypto.randomUUID()}`,
    type: "proposal",
    position: { x: 300 + Math.floor(Math.random() * 120), y: 180 + Math.floor(Math.random() * 240) },
    data: {
      proposalType,
      name,
      status: "pending",
      reason: "Generated by AI planner",
      proposedDefinition,
      createdAt: new Date().toISOString(),
      source: "ai_generator",
    },
  };
}

export function generationToProposalNodes(payload: GenerationResponse): ProposalNode[] {
  const nodes: ProposalNode[] = [];
  for (const skill of payload.skills) {
    nodes.push(
      proposalNodeBase(
        skill.name,
        {
          name: skill.name,
          fileName: `${skill.name}.yaml`,
          description: skill.description,
          inputs: skill.inputs,
          outputs: skill.outputs,
          requires: skill.requires,
          produces: skill.produces,
          validations: skill.validations,
        },
        "proposed_skill",
      ),
    );
  }

  for (const artifact of payload.artifacts) {
    nodes.push(
      proposalNodeBase(
        artifact.fileName,
        {
          fileName: artifact.fileName,
          name: artifact.fileName,
          artifactType: artifact.artifactType,
          description: artifact.description,
        },
        "proposed_artifact",
      ),
    );
  }

  for (const change of payload.contractChanges) {
    nodes.push(
      proposalNodeBase(
        `contract_change_${change.stepName}`,
        {
          stepName: change.stepName,
          requires: change.requires ?? [],
          produces: change.produces ?? [],
          validations: change.validations ?? [],
        },
        "proposed_contract_change",
      ),
    );
  }
  return nodes;
}

/**
 * Converts AI generation output directly into a fully-wired Workflow (no proposals).
 * Used by "Generate Draft" mode on a blank canvas.
 */
export function generationToDraftWorkflow(payload: GenerationResponse, name: string): Workflow {
  const now = new Date().toISOString();

  const skillNodes: Workflow["nodes"] = payload.skills.map((skill, i) => ({
    id: `skill_${uid()}`,
    type: "skill" as const,
    position: { x: 200, y: 80 + i * 140 },
    data: {
      name: skill.name,
      fileName: `${skill.name}.yaml`,
      description: skill.description,
      inputs: skill.inputs,
      outputs: skill.outputs,
      requires: skill.requires,
      produces: skill.produces,
      validations: skill.validations,
      tags: [],
      enabled: true,
      version: 1,
    },
  }));

  // Collect all unique artifact fileNames from skill contracts + explicit declarations
  const artifactFileNames = new Set<string>();
  for (const skill of payload.skills) {
    for (const f of [...skill.inputs, ...skill.outputs]) artifactFileNames.add(f);
  }
  for (const art of payload.artifacts) artifactFileNames.add(art.fileName);

  const artifactMeta = new Map(payload.artifacts.map((a) => [a.fileName, a]));

  const artifactNodes: Workflow["nodes"] = Array.from(artifactFileNames).map((fileName, i) => {
    const meta = artifactMeta.get(fileName);
    return {
      id: `artifact_${uid()}`,
      type: "artifact" as const,
      position: { x: 560, y: 80 + i * 100 },
      data: {
        name: fileName,
        fileName,
        artifactType: (meta?.artifactType ?? "md") as "md" | "json" | "yaml" | "csv" | "xlsx" | "txt" | "other",
        description: meta?.description,
        status: "unknown" as const,
      },
    };
  });

  const draft: Workflow = {
    id: `wf_${uid()}`,
    name,
    version: "1.0.0",
    createdAt: now,
    updatedAt: now,
    description: payload.summary,
    nodes: [...skillNodes, ...artifactNodes],
    edges: [],
    metadata: { graphVersion: "1.0.0" },
  };

  return syncSkillContractsFromGraph(buildEdgesFromContracts(draft));
}
